spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/blog?useUnicode=true&characterEncoding=UTF-8&useSSL=true
    username: root
    password: Wzy1gqqbuu-
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  redis:
    port: 6379
    host: 127.0.0.1
  jackson:
    default-property-inclusion: non_null
  mvc:
    dispatch-options-request: true
#server:
#  port: 8077
#  servlet:
#    context-path: /blog

